### ISSUE TITLE
Error thrown when executing `drome` in virgin directory

### ISSUE THREAD

**Issue by mikeerickson** [dromejs/drome#26]
## Bug Report

When executing drome in a new project directory (no configuration, etc found) the following error is thrown

```bash
TypeError: projectConfig is not a function
    at getTaskList (/Users/mikee/Documents/code/oss/drome/lib/utils.js:59:46)
    at showHelp (/Users/mikee/Documents/code/oss/drome/lib/cliUtils.js:12:32)
    at Promise (/Users/mikee/Documents/code/oss/drome/lib/task.js:61:17)
    at new Promise (<anonymous>)
    at cliCommand (/Users/mikee/Documents/code/oss/drome/lib/task.js:57:12)
    at run (/Users/mikee/Documents/code/oss/drome/lib/task.js:24:22)
    at drome (/Users/mikee/Documents/code/oss/drome/lib/drome.js:25:18)
    at Object.<anonymous> (/Users/mikee/Documents/code/oss/drome/bin/drome.js:56:5)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
```

**Comment by mikeerickson** [comment]
@kodipe I will fix this issue, just wanted to document it so I have an issue to fix against.  I will get it cured for the `0.5.0` release

**Comment by kodipe** [comment]
@mikeerickson Thanks for report! Feel free to fix that :)

**Comment by mikeerickson** [comment]
I will fix this tomorrow, I am going to sleep

**Comment by mikeerickson** [comment]
See PR https://github.com/dromejs/drome/pull/30
